### PR TITLE
WIP: Prototype of New Evaluator

### PR DESCRIPTION
**Pull request by cortner**
this PR will implement a first prototype of a potential evaluator for ACE1.jl using the new kernels provided by ACEcore and Polynomials4ML

it needs [THIS PR OF ACE1X](https://github.com/ACEsuit/ACEcore.jl/pull/19) to work

CC @tjjarvinen @casv2

### CODE REVIEW

**Comment by cortner** [comment]
First benchmark - and this is before I put in *any* optimizations or even the batching: 
```
Old:   27.875 μs (566 allocations: 28.02 KiB)
New:   9.208 μs (12 allocations: 55.34 KiB)
```

**Comment by casv2** [comment]
Wow! Very nice

**Comment by cortner** [comment]
just recording latest experiments ... proper batched evaluation throughout gives WORSE performance rather than improved performance. I have probably done something wrong, either bad usage of cache or bad array access patterns. In any case this whole story seems less trivial than I had hoped.

**Comment by cortner** [comment]
a few fixes have been implemented, but the performance is still not that great.

**Comment by cortner** [comment]
I'm going to close this since P4ML has move far beyond this, but leave the dangling branch in case we want to look at it in the future.

**Pull request closed without merging**
