### PR TITLE
Purify

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
This branch implements the pureRPIbasis in a new module 'Purify' and its tests. We can now create pure basis with pure_rpibasis = ACE1x.Purify.pureRPIBasis(rpibasis).

The unit tests of it basically follows pure2b module with single species & multi species version. An orthogonality test for the single species test is also included.

I did not name the utils functions that I used to construct the pure basis carefully for now but it should be done later. The current implementation also do not taking care too much on the efficiency of construction.

### CODE REVIEW

**Comment by cortner** [comment]
@casv2 and @bernstei  --  I wonder whether you'd like to test this with HAL, BRR, ARD, to see whether it gives better uncertainties or better BRR scores when you go to 3-correlations?

**Comment by casv2** [comment]
Absolutely! Should I wait for the merge?

**Comment by cortner** [comment]
Maybe if I can manage to test and merge this weekend

**Comment by cortner** [comment]
Let's see if I can manage to put together an interface for this over the weekend?

**Comment by cortner** [comment]
@CheukHinHoJerry  -- if you continue to work on this branch, pleaes make sure to pull my latest cchanges first.

**Comment by cortner** [comment]
Look really really good. There is one thing I'd like to have before merging: incorporate this into the user-facing interface `acemodel` etc.

secondly, if we can add a test that guarantees that the two bases span the same space ? @CheukHinHoJerry we discussed this if I remember correctly how to do this?

**Comment by CheukHinHoJerry** [comment]
Thanks for reviewing - RE checking span : I think what we did before was to create two design matrix A1, A2 and make use of thin QR factorization Qi, Ri = qr(Ai) to check Q1 * Q1' * A2 = A2 and Q2 * Q2' * A1 = A1.

**Comment by cortner** [comment]
did you check this and what was the outcome?

**Comment by CheukHinHoJerry** [comment]
For no envelope function, the two basis span the same space, which is expected since any order $N$ 'self interaction' can be approximated in terms of order $< N$ basis.

But with envelope function if seems that they are not (from the numerical test). My guess is that it is because:

Let $f$ be envelope function. Let $A$ and $A'$ be basis without and with envelope. For the impure basis, we have 

image

The 'self interaction' at order $N$ is in form of $g f^{N}$, where $g$ can be expressed by basis $A$ of order less than $N$. But in the expansion of $A'$ we can at most find terms like $g f^{N -1}$ from the lower order.

I added the span test for the single species and fixed a bug. Please pull and see the update.

**Comment by cortner** [comment]
Hi @CheukHinHoJerry  -- I've added the pure basis construction into the `acemodel` interface. Would you be willing check that this does "the right thing"? I.e. can you add a quick test that this really constructs a purified basis? 

After that, we should publish some brief docs how to generate the three kinds of bases - standard, pure2b, pure, with and without 2b, so that everybody can easily test all options. Then we can merge and ask Cas to test this.

Thank you for this really excellent work!!

**Comment by cortner** [comment]
very odd - there appears to be a bug when converting the basis to a calculator. I get the following stacktrace and will try to come up with a MWE.
```
    nested task error: BoundsError: attempt to access 3373-element Vector{ComplexF64} at index [1:4732]
    Stacktrace:
      [1] throw_boundserror(A::Vector{ComplexF64}, I::Tuple{UnitRange{Int64}})
        @ Base ./abstractarray.jl:703
      [2] checkbounds
        @ ./abstractarray.jl:668 [inlined]
      [3] view
        @ ./subarray.jl:177 [inlined]
      [4] evaluate!(A::Vector{ComplexF64}, tmp::NamedTuple{(:BJ, :tmpJ, :BY, :tmpY, :dBJ, :tmpdJ, :dBY, :tmpdY), Tuple{Vector{Float64}, Nothing, Vector{ComplexF64}, NamedTuple{(:P,), Tuple{Vector{Float64}}}, Vector{Float64}, Nothing, Vector{StaticArraysCore.SVector{3, ComplexF64}}, NamedTuple{(:P, :dP), Tuple{Vector{Float64}, Vector{Float64}}}}}, basis::BasicPSH1pBasis{Float64, 1, ACE1.OrthPolys.TransformedPolys{Float64, ACE1.Transforms.MultiTransform{1, ACE1.Transforms.AffineT{Float64, ACE1.Transforms.Agnesi2Transform{Float64, Int64}}}, ACE1.OrthPolys.OrthPolyBasis{Float64}, ACE1.OrthPolys.OneEnvelope}}, Rs::SubArray{StaticArraysCore.SVector{3, Float64}, 1, Vector{StaticArraysCore.SVector{3, Float64}}, Tuple{UnitRange{Int64}}, true}, Zs::SubArray{AtomicNumber, 1, Vector{AtomicNumber}, Tuple{UnitRange{Int64}}, true}, z0::AtomicNumber)
        @ ACE1 ~/.julia/packages/ACE1/3Zhx6/src/oneparticlebasis.jl:15
      [5] evaluate_d!(dEs::Vector{StaticArraysCore.SVector{3, Float64}}, tmpd::NamedTuple{(:R, :Z, :dV, :tmpd_basis1p, :AA, :B, :A, :dA), Tuple{Vector{StaticArraysCore.SVector{3, Float64}}, Vector{AtomicNumber}, Vector{StaticArraysCore.SVector{3, Float64}}, NamedTuple{(:BJ, :tmpJ, :BY, :tmpY, :dBJ, :tmpdJ, :dBY, :tmpdY), Tuple{Vector{Float64}, Nothing, Vector{ComplexF64}, NamedTuple{(:P,), Tuple{Vector{Float64}}}, Vector{Float64}, Nothing, Vector{StaticArraysCore.SVector{3, ComplexF64}}, NamedTuple{(:P, :dP), Tuple{Vector{Float64}, Vector{Float64}}}}}, Vector{ComplexF64}, Vector{ComplexF64}, Vector{ComplexF64}, Matrix{StaticArraysCore.SVector{3, ComplexF64}}}}, V::PIPotential{Float64, 1, PIBasis{BasicPSH1pBasis{Float64, 1, ACE1.OrthPolys.TransformedPolys{Float64, ACE1.Transforms.MultiTransform{1, ACE1.Transforms.AffineT{Float64, ACE1.Transforms.Agnesi2Transform{Float64, Int64}}}, ACE1.OrthPolys.OrthPolyBasis{Float64}, ACE1.OrthPolys.OneEnvelope}}, 1, ACE1.DAGEvaluator}, ACE1.DAGEvaluator, 0}, #unused#::ACE1.DAGEvaluator, Rs::SubArray{StaticArraysCore.SVector{3, Float64}, 1, Vector{StaticArraysCore.SVector{3, Float64}}, Tuple{UnitRange{Int64}}, true}, Zs::SubArray{AtomicNumber, 1, Vector{AtomicNumber}, Tuple{UnitRange{Int64}}, true}, z0::AtomicNumber)
        @ ACE1 ~/.julia/packages/ACE1/3Zhx6/src/pipot.jl:367
      [6] evaluate_d!
        @ ~/.julia/packages/ACE1/3Zhx6/src/pipot.jl:178 [inlined]
....
```

**Comment by cortner** [comment]
This reproduces the error I think: 
```julia 
using ACE1x
JuLIP.usethreads!(false)
model = acemodel(elements = [:Ni,], order = 3, totaldegree = [ 20, 16, 12 ] , 
                  pure2b = false, pure = true)
ACE1x._set_params!(model, randn(length(model.basis)))
at = bulk(:Ni, cubic=true) * 2
forces(model.potential, at)
```

And here is a my status of `ACE1x`: 
```
(ACE1x) pkg> status
Project ACE1x v0.0.6
Status `~/gits/ACE1x.jl/Project.toml`
  [e3f9bc04] ACE1 v0.11.6
  [945c410c] JuLIP v0.14.1
  [d9ec5142] NamedTupleTools v0.14.3
  [189a3867] Reexport v1.2.2
  [f07d36f2] RepLieGroups v0.0.1
  [ddb6d928] YAML v0.4.8
  [37e2e46d] LinearAlgebra
  [2f01184e] SparseArrays
  [10745b16] Statistics
```

and my git status: 
```
(base) ortner@CosmicCrisp ACE1x.jl % git status
On branch purify
Your branch is up to date with 'origin/purify'.
```

**Comment by cortner** [comment]
@CheukHinHoJerry  -- Would you be willing to see if you can find out what the problem is?  I will also try.

**Comment by CheukHinHoJerry** [comment]
Sure. I will look into the error, check with the acemodel and try to make some example on three kinds of basis later tonight. Thanks for trying this out.

**Comment by CheukHinHoJerry** [comment]
I think the reason is that I didn't carefully construct the 1 particle basis such that many useless 1 particle basis are created. If 

`model_tmp = JuLIP.alloc_temp_d(model.potential.components[2], at)`

then we have:

`length(model_tmp_A) = 4732`

but 

`length(model_tmp_AA) = 3373`

which causes the error. I will try to think of further restricting the number of 1 particle basis and fix that asap.

**Comment by cortner** [comment]
but why is this not a problem for the basis and only for the evaluator? Also it seems this happens only for `forces` but not for `evaluate_d`

**Comment by cortner** [comment]
here is a reduced MWE, you probably got further already, I'm just posting here to document what I do so I can track it down later.
```julia
using ACE1x, JuLIP 
JuLIP.usethreads!(false)
model = acemodel(elements = [:Ni,], order = 3, totaldegree = [ 10, 8, 6 ] , 
                  pure2b = false, pure = true)
ACE1x._set_params!(model, randn(length(model.basis)))
V = model.potential.components[2]
Nat = 10 
z0 = AtomicNumber(:Ni)
ZZ = fill(z0, Nat)
Rs = [ ACE1.Random.rand_sphere() * (2.7 + 2 * rand()) for i = 1:Nat]
JuLIP.evaluate_d(V, Rs, ZZ, z0)
```

**Comment by cortner** [comment]
@CheukHinHoJerry  -- I now understand your point, well done for tracking this down. 

It looks a bit like a brittleness in ACE1.jl. But more immediately it is caused by the fact that the pibasis is not constructed correctly, is that possible? Maybe the DAG has to be recomputed and we forgot to do that?

Specifically, I wonder why the line 
```julia
   pibasis_x = ACE1.pibasis_from_specs(b1p_x, Tuple(spec_x_list))
```
doesn't fix everything? Maybe this is where the bug really lives?

**Comment by CheukHinHoJerry** [comment]
@cortner Yes - I think I got to similar point and I agree that maybe we did not initialize the DAG correctly.

**Comment by cortner** [comment]
But that shouldn't cause this bug I think

**Comment by CheukHinHoJerry** [comment]
@cortner -- I think the problem is that in this function at ACE1/src/oneparticlebasis.jl/:

```julia
function evaluate!(A, tmp, basis::OneParticleBasis, Rs, Zs::AbstractVector, z0)
   fill!(A, 0)
   iz0 = z2i(basis, z0)
   for (R, Z) in zip(Rs, Zs)
      iz = z2i(basis, Z)
         add_into_A!((@view A[basis.Aindices[iz, iz0]]), tmp, basis, R, iz, iz0)
   end
   return A
end
```
the `A[basis.Aindices[iz, iz0]]` argument in `add_into_A!` assumes that `basis.Aindices` (indices of 1pbasis) is a subset of AA basis initialized by `alloc_temp_d` when calling `forces(...)`. To fix this maybe we have to take care of it in the `evaluate!` function.

**Comment by cortner** [comment]
Thank you. I'll try to look into it tonight. I am also thinking that maybe I could finally implement sparsification which would automatically fix this I think.

**Comment by cortner** [comment]
I pushed what might be a temporary fix to ACEsuit/ACE1.jl#72 . I haven't had a chance to test this yet. But at least it evaluates.

**Comment by CheukHinHoJerry** [comment]
Thank you for the update. I will look at it tonight.

**Comment by CheukHinHoJerry** [comment]
Hi @cortner - I am looking into the `acemodel` interface and have the following questions. Could you please give me some suggestions?

1. Currently the `pure2b` argument is overriding the `pure` argument but I think it should be converse?
2. There is a `delete2b` argument for the pure2b basis which delete all the 2 body basis from the output. Do you think it is better if I introduce a new argument `delete = Union{Array{Int}, Int}` for the pure basis that allow the users to select which body order they want to 'delete'?
3. Do you think we should allow the user to have control over purification up to a certain order? e.g. for order = 5 only purify basis up to order = 3. I think this will provide some more flexibility for analysis of the new basis.

After confirming the above and finish up the test for `acemodel` I will make some easy examples for different kinds of basis (e.g. standard, pure2b, pure, basis deleting certain order).

**Comment by cortner** [comment]
1. correct - I already fixed that locally while debugging but haven't pushed this yet

2. that would be Fantastic. 

3. that seems an unnecessary amount of flexibility but if it is easy then it can't hurt.

Let me know what you are planning to fix now since I have a few things locally but I'll stop working on those if you are already going in the right direction. 

I now really think this is an ACE1.jl bug and it should be fixed at my end. But having a workaround would surely be nice :)

**Comment by CheukHinHoJerry** [comment]
@cortner Thank you for your comment. I would make changes according to your suggestions.

I only have some local changes on 1. and 2. with some testing code on the acemodel but anything else is not significant. My end has nothing very technical so maybe I can commit after your update in case there is any conflict.

**Comment by casv2** [comment]
I'm sorry to bother, but what is the status on this? I think we really need this and it will move ACE forward.

**Comment by cortner** [comment]
> I'm sorry to bother, but what is the status on this? I think we really need this and it will move ACE forward.

probably later today.

**Comment by cortner** [comment]
got some nice-ish initial results. I'll now merge and tag it so you can try it out in a more realistic setting ...

**Comment by cortner** [comment]
Basis ~ 300, ca 8000 observations, RRQR: 
```
Energy Error
┌────┬────────┬────────┬────────┐
│    │  dirty │ pure2b │   pure │
├────┼────────┼────────┼────────┤
│ Ni │  2.548 │  8.008 │  0.865 │
│ Cu │  3.009 │  2.446 │  0.517 │
│ Li │  0.689 │  7.086 │  1.076 │
│ Mo │ 17.727 │ 15.433 │ 11.171 │
│ Si │  3.582 │  4.736 │  4.441 │
│ Ge │  8.379 │  6.265 │  6.942 │
└────┴────────┴────────┴────────┘
Force Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.037 │  0.037 │ 0.018 │
│ Cu │ 0.027 │  0.027 │ 0.009 │
│ Li │ 0.011 │  0.035 │ 0.008 │
│ Mo │  0.15 │  0.155 │ 0.141 │
│ Si │ 0.097 │  0.106 │  0.09 │
│ Ge │ 0.069 │  0.073 │ 0.066 │
└────┴───────┴────────┴───────┘
```

**Comment by cortner** [comment]
Basis ~ 300, ca 8000 observations, BLR: 
```
┌────┬────────┬────────┬────────┐
│    │  dirty │ pure2b │   pure │
├────┼────────┼────────┼────────┤
│ Ni │   0.68 │   0.57 │  1.646 │
│ Cu │  1.304 │  1.373 │  0.631 │
│ Li │  1.024 │   0.84 │  0.761 │
│ Mo │ 13.192 │ 18.219 │ 11.943 │
│ Si │  3.731 │  3.467 │   4.37 │
│ Ge │  8.146 │  7.152 │  6.492 │
└────┴────────┴────────┴────────┘
Force Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.021 │  0.021 │ 0.017 │
│ Cu │ 0.009 │  0.008 │ 0.007 │
│ Li │ 0.007 │  0.006 │ 0.006 │
│ Mo │  0.14 │  0.144 │ 0.136 │
│ Si │ 0.091 │  0.091 │ 0.085 │
│ Ge │ 0.067 │  0.068 │ 0.066 │
└────┴───────┴────────┴───────┘
```

**Comment by cortner** [comment]
with an even smaller dataset (forgot the size, but this is probably ca 1-2k observations) 
```
┌────┬─────────┬─────────┬────────┐
│    │   dirty │  pure2b │   pure │
├────┼─────────┼─────────┼────────┤
│ Ni │  21.514 │  58.261 │ 15.283 │
│ Cu │   4.235 │  24.864 │  6.149 │
│ Li │   1.101 │   1.094 │  0.854 │
│ Mo │ 133.395 │ 132.162 │ 85.127 │
│ Si │   7.211 │   5.476 │  5.282 │
│ Ge │  17.573 │  26.836 │  9.084 │
└────┴─────────┴─────────┴────────┘
Force Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.025 │  0.025 │ 0.019 │
│ Cu │ 0.025 │  0.027 │ 0.016 │
│ Li │ 0.008 │  0.008 │ 0.007 │
│ Mo │ 0.178 │  0.181 │ 0.171 │
│ Si │ 0.106 │  0.117 │ 0.098 │
│ Ge │ 0.071 │  0.075 │ 0.069 │
└────┴───────┴────────┴───────┘
```

**Comment by cortner** [comment]
basis ~ 300, full dataset ~ 80k
```
Energy Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.406 │  0.397 │  0.42 │
│ Cu │ 0.289 │  0.282 │ 0.259 │
│ Li │ 0.242 │  0.237 │ 0.248 │
│ Mo │ 3.103 │   3.23 │ 2.924 │
│ Si │ 3.461 │  3.514 │ 3.559 │
│ Ge │ 2.749 │  2.768 │ 2.149 │
└────┴───────┴────────┴───────┘
Force Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.018 │  0.018 │ 0.016 │
│ Cu │ 0.007 │  0.007 │ 0.006 │
│ Li │ 0.006 │  0.006 │ 0.006 │
│ Mo │ 0.122 │  0.122 │ 0.111 │
│ Si │ 0.085 │  0.086 │  0.08 │
│ Ge │ 0.064 │  0.064 │ 0.062 │
└────┴───────┴────────┴───────┘
```

**Comment by cortner** [comment]
large basis ~ 1k, large dataset ~ 30k to 80k, RRQR not BLR!!
```

Energy Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.323 │  0.336 │ 0.334 │
│ Cu │ 0.269 │  0.231 │  0.19 │
│ Li │ 0.158 │  0.164 │ 0.196 │
│ Mo │ 3.078 │  3.092 │  3.09 │
│ Si │ 2.327 │  2.295 │ 2.118 │
│ Ge │ 2.332 │  2.174 │ 2.094 │
└────┴───────┴────────┴───────┘
Force Error
┌────┬───────┬────────┬───────┐
│    │ dirty │ pure2b │  pure │
├────┼───────┼────────┼───────┤
│ Ni │ 0.015 │  0.015 │ 0.014 │
│ Cu │ 0.006 │  0.006 │ 0.005 │
│ Li │ 0.005 │  0.005 │ 0.005 │
│ Mo │ 0.098 │  0.099 │ 0.095 │
│ Si │ 0.067 │  0.066 │ 0.069 │
│ Ge │ 0.051 │  0.051 │ 0.052 │
└────┴───────┴────────┴───────┘
```

**Comment by casv2** [comment]
Thanks very much both of you! I’m mostly hoping this improves evidence maximisation convergence and uncertainties too

**Comment by cortner** [comment]
We see improvements on small datasets but they are not systematic. I wouldn't get my hopes up yet. After LA maybe we can discuss how to understand what is going on?

**Pull request merged**
