### PR TITLE
Clean up purified basis as in pure2b, bug fix in pure basis and add consistency test for different ace models

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
Basically I follow what e951bef do and clean up the pure basis while making sure all the previous tests passes

I also do some quick performance fix on the construction of `A2Bmap` of pure basis.

### CODE REVIEW

**Comment by cortner** [comment]
Thank you, let's make the performance a separate PR? I can test and merge later.

**Comment by CheukHinHoJerry** [comment]
@cortner I think this is ready to merge too. Could you please take a look when you are free?

**Comment by cortner** [comment]
I'm running the tests locally as well. Shall I trigger a patch release?

**Comment by CheukHinHoJerry** [comment]
I think yes. The bug fix is minor but would affect the fitting result in some sense so it's better to be a patch release.

Should we also add checks on julia 1.9 and 1.10 for our CI?

**Comment by cortner** [comment]
registered as v"0.1.5"

**Pull request merged**
