### PR TITLE
WIP: purification clean up and performance fix

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
No need to merge for now, still trying to fix it.

### CODE REVIEW

**Comment by cortner** [comment]
what is happening with this PR? Is it worth taking another look and merging it?

**Comment by CheukHinHoJerry** [comment]
This PR was trying to assemble the purification matrix faster and is done (but I forget about this, sorry) . I will take another look to make sure it is compatible with main and then we can consider merging this?

**Comment by CheukHinHoJerry** [comment]
I think this is now ready. This doesn't changes anything from the user end. Could you please take a look to see if extra tests are needed?

**Review by cortner — APPROVED** [review]
looks good. I'll double-check the tests though before merging.

**Pull request merged**
