### PR TITLE
Other radial transforms

### PR DESCRIPTION
**Pull request by JPDarby**
Tweak to use the IdentityTransform(), only tested with this. Changes are in lines 183-190.

### CODE REVIEW

**Comment by cortner** [comment]
Thank you. Looks ok, I want to test it locally later since the CI is broken. (I need to fix that too...)

I do have a request, I don't know how easy it is ... In the future, can you ask your editor to not fix my whitespace? editors are opinionated about this and as a result I have hundreds of lines of git-changes to read that are only whitespace changes.

**Comment by cortner** [comment]
Can you confirm that the point of this is to convert the simple transform into a multi transform so that it exports correctly?

**Comment by JPDarby** [comment]
Yes exactly, changing it from a simple transform to a multi transform seemed to do the trick. I didn't dive too deep into why this was needed though, just copied from the agnesi transform that was already there.

>  In the future, can you ask your editor to not fix my whitespace?

Yes sorry about that

**Comment by cortner** [comment]
hm - I'm just going to merge and then check ... easier.

**Comment by cortner** [comment]
no need at all to apologize, thanks for taking initiative.

**Comment by cortner** [comment]
@JPDarby  -- this is now tagged as 0.1.1. Please add this to your Project.toml

**Comment by JPDarby** [comment]
Thanks!

**Pull request merged**
